name: Build
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Check quality gate
        run: if curl -v --silent -u $SONAR_PASSWORD https://sonar-staging.nmarket.tech/api/qualitygates/project_status?projectKey=matajer 2>&1  | grep "ERROR"; then exit 1; else exit 0; fi
        env:
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}